### ISSUE TITLE
Questions about pre-training data

### ISSUE THREAD

**Issue by HelloWorldLTY** [bowang-lab/Orthrus#6]
Hi, I notice that in the example, there exists T in mRNA information. Does it mean you utilize cDNA information of mRNA for training? It seems that other RNA foundation model utilizes ACGU as tokens: https://github.com/ml4bio/RNA-FM. Are there any advantages for not including U? If yes, can Orthrus be used to generate DNA embeddings? Thanks a lot.

**Comment by IanShi1996** [comment]
Hi!

Using ACGT vs ACGU as the vocabulary of one-hot-encoded tokens should actually be equivalent -- in the input sequence, you can just replace the U/Ts to match what the model uses, since T's are replaced by U's during transcription. On our end, we used T because we constructed the RNA transcripts used for pre-training by splicing together annotated genomic assemblies, and didn't convert the T -> U afterwards (though it might be more accurate to do so)! 

This means that Orthrus can accept DNA as an input and generate embeddings, but note Orthrus is not pre-trained for performance on DNA tasks. For example, intronic / intergenic regions are not seen during pre-training, so any tasks dependant on information in those regions may not perform well. However, its also possible that Orthrus will be performant on DNA tasks that depend on the CDS / UTR regions.

**Comment by HelloWorldLTY** [comment]
I see, thanks. I have this problem because I believe the DNABERT-2 or HyenaDNA cannot directly process RNA sequences, and T/U might not be equvalient due to the frequence problem, as not every DNA sequence will be transferred to corresponding RNA.

**Comment by phil-fradkin** [comment]
Your intuition is correct - if you take a look at our paper, we actually benchmark these models and find they're not a great fit for RNA property prediction tasks. 

There appears to be a distribution shift between DNA tasks and RNA. Although you can technically encode sequences and generate model embeddings for these, they don't seem to be effective at encoding RNA properties. One big challenge seems to be the distribution shift, another is the limited context window. Mature RNA sequences can be quite long which makes it challenging for transformer based models to capture the relationship between distance parts of the sequence.
